
ARDUINO_DIR  = /home/christoph/Programs/arduino-1.5.2

TARGET       = hometrainer
ARDUINO_LIBS =  libraries/LiquidCrystal hardware/arduino/avr/libraries/EEPROM

BOARD_TAG    = mini
MCU = atmega328p
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE = 115200

include $(ARDUINO_DIR)/Arduino.mk


