
ARDUINO_DIR  = /home/christoph/Programs/arduino-1.5.2

TARGET       = hometrainer
ARDUINO_LIBS =  libraries/LiquidCrystal hardware/arduino/avr/libraries/EEPROM

BOARD_TAG    = mega
ARDUINO_PORT = /dev/ttyUSB0


include $(ARDUINO_DIR)/Arduino.mk


